---
driver:
  name: vagrant
  require_chef_omnibus: true
  ssh:
    insert_key: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: client
    run_list:
      - recipe[consul-got::client]
    attributes:
  - name: server
    run_list:
      - recipe[consul-got::server]
    attributes:
